Chart.yaml
templates/NOTES.txt
templates/_helpers.tpl
templates/kotsadm-config.yaml
templates/kotsadm-default-configvalues.yaml
templates/kotsadm-default-license.yaml
templates/kotsadm-deployment.yaml
templates/kotsadm-role.yaml
templates/kotsadm-rolebinding.yaml
templates/kotsadm-service.yaml
templates/kotsadm-serviceaccount.yaml
templates/minio-service.yaml
templates/minio-statefulset.yaml
templates/postgres-configmap.yaml
templates/postgres-service.yaml
templates/postgres-statefulset.yaml
templates/secret-api-cluster-token.yaml
templates/secret-api-encryption.yaml
templates/secret-jwt.yaml
templates/secret-pg.yaml
templates/secret-s3.yaml
templates/secret-shared-password.yaml
templates/tests/test-connection.yaml
values.yaml

As title describes..change chart name to admin-console.
Performed successful helm package and deployment of admin console with this new naming.

change chart name to admin-console

---

.github/workflows/publish-production.yaml
.github/workflows/publish-staging.yaml

1) publish chart to staging on merge to main
2) publish chart to prod on tag creation
The secrets need to be created and am speaking with Chase about this.  I have tested both work flows and both work when proper user/pass provided.
1) prod test run: https://github.com/replicatedhq/kots-helm/runs/6492270041?check_suite_focus=true
2) staging test run: https://github.com/replicatedhq/kots-helm/runs/6492270008?check_suite_focus=true

add github workflows for publishing to staging and prod registries

---

.github/workflows/publish-production.yaml
.github/workflows/publish-staging.yaml
.helmignore
Chart.yaml.tmpl
README.md
RELEASING.md
build-local.sh
templates/kotsadm-config.yaml
templates/kotsadm-default-configvalues.yaml
templates/kotsadm-default-license.yaml
templates/kotsadm-deployment.yaml
templates/minio-statefulset.yaml
templates/postgres-statefulset.yaml
templates/secret-shared-password.yaml
values.yaml.tmpl

- Removes hardcoded images.  Images are now taken from kots repo's image manifest that matches the tagged version.
- Staging releases are now created with `alpha` tags instead of merges to main branch
- Production releases are created with non-`alpha` tags

Helm chart versions match kots versions

---

templates/kotsadm-service.yaml

Set default port to 80.  This was already done in the values yaml, we just needed to use the value
fixes:
https://app.shortcut.com/replicated/story/50965/admin-console-service-should-default-to-listening-on-80-not-3000

use service port value

---

README.md
templates/secret-shared-password.yaml

Current password is preserved unless a password value is specified in the upgrade command
```
helm upgrade admin-console oci://registry.replicated.com/library/admin-console --set password=password123
```

Don't override existing password with default on upgrades

---

templates/kotsadm-service.yaml

Allows for specifying `.service.nodePort` in the values file for setting the kotsadm Service nodePort.

Allow specifying Service nodePort

---

templates/kotsadm-deployment.yaml
values.yaml.tmpl

During development it is possible to run kots on an arm mac. While not the default or supported, this change would allow me to override the configuration so I can do this.

feat: move the affinity settings to the values file

---

templates/kotsadm-application.yaml

using indent to make sure the application.yaml is placed where it should be inside the values.yaml used to install the kots helm chart.

bug: indent application yaml file inside config map

---

templates/kotsadm-service.yaml

kotsadm relies on this to generate the node join command

ensure the nodeport is named admin-console

---

templates/secret-api-encryption.yaml

fixes the templating in the `kotsadm-encryption` secret so that the encryption key generated is valid

fix invalid encryption key generation

---

templates/secret-api-encryption.yaml

Fixes an issue where the encryption key gets base64 encoded every time the Helm chart gets upgraded.

Base64 decode encryption key when reading it from existing secret

---

templates/abandon-resources-hook.yaml
templates/kotsadm-statefulset.yaml
templates/secret-shared-password.yaml
values.yaml.tmpl

new value: `passwordSecretRef` takes a secret ref i.e: `map[key, name]` to tell kots what secret to use instead of the default. 
if set, it overrides password secret generation

Make password secret optional

---

templates/kotsadm-statefulset.yaml
values.yaml.tmpl

This PR adds an `extraEnv` value to the KOTS helm chart to allow setting additional environment variables on the `kotsadm` StatefulSet (ex: for a proxy).

add extraEnv value to allow setting additional environment variables

---

templates/kotsadm-deployment.yaml

Reverts replicatedhq/kots-helm#50
We don't otherwise restart kots at this point, and avoiding it would be good

Revert "set IS_HA env var based on helm chart value"

---

values.yaml.tmpl

This is to support running a local EC dev env (on Mac)

Allow running on arm64 nodes

---

templates/secret-rqlite.yaml

When setting NO_PROXY env var to include .cluster.local this will not work with the shorthand dns.

fix(proxy): use fqdn for kotsadm-rqlite address

---

templates/migrate-s3-hook.yaml

When setting NO_PROXY env var to include .cluster.local this will not work with the shorthand dns.

fix: use fqdn for kotsadm-minio for proxy support

---

templates/kotsadm-deployment.yaml

this must be `configMap`, when manually editing the deployment and adding a `configmap` entry the api reports the following error:
```
decoding error: unknown field "spec.template.spec.volumes[3].configmap"
```

bug: fix config map entry on deployment

---

templates/keep-resources-hook.yaml
templates/migrate-pvc-hook.yaml
templates/migrate-s3-hook.yaml

If a hook fails or a helm operation exits before success the hook job will not be deleted. This change makes automation of helm charts more resilient as subsequent attempts will delete the hook.

fix: add hook-delete-policy before-hook-creation

---

templates/kotsadm-deployment.yaml

Two kots pods should not be running at the same time. This is causing kots to serve the old ui after an update.

fix: kotsadm deployment strategy recreate

---

templates/kotsadm-deployment.yaml
values.yaml.tmpl

This PR adds support for adding custom volumes to the kotsadm deployment. 
* Adds extraVolumes and extraVolumeMounts fields to values.yaml.tmpl, allowing users to define custom volumes and mounts
* Updates the kotsadm-deployment.yaml template to render the custom volumes and mounts

feat: Add support for extraVolumes and host CA bundle integration
